apiVersion: batch/v1
kind: Job
metadata:
  name: redis-init
spec:
  template:
    spec:
      containers:
      - name: redis-init
        image: satomic/redis-init
        command: ["bash", "/poc/poc.sh"]
      restartPolicy: Never
  backoffLimit: 4